name: DEPLOY TO DEVELOP

on:
  push:
    branches:
      - 'DEVELOP'

jobs:
  deploy-to-preprod:
    runs-on: ubuntu-latest
    env:
      SF_CLI_URL: https://developer.salesforce.com/media/salesforce-cli/sf/channels/stable/sf-linux-x64.tar.xz

    steps:
    - uses: actions/checkout@v1
    - name: Install SF CLI
      run: |
        npm install @salesforce/cli --global
        sf update

    - name: Install TEXEI SFDX PLUGIN
      run: |
        echo 'y' | sf plugins install texei-sfdx-plugin
        
    - name: Connect to DEVELOP Sandbox
      run: |
        echo ${{ secrets.SFDX_AUTHURL_DEVELOP }} > ./authfile
        sf auth sfdxurl store --sfdx-url-file authfile --alias SANDBOX_DEVELOP --set-default
    
    - name: Create new empty Profiles
      run: |
        sf texei skinnyprofile create --target-org SANDBOX_DEVELOP

    - name: Deploy on DEVELOP Sandbox
      run: |
        sf project deploy start --source-dir force-app --test-level RunLocalTests --target-org SANDBOX_DEVELOP --wait ${{ secrets.SFDX_TIMEOUT }} --ignore-conflicts --dry-run